import './css/style.css'

import { Inter, Kumbh_Sans } from 'next/font/google'

import Header from '@/components/ui/header'
import Banner from '@/components/banner'
import { Bricolage_Grotesque } from 'next/font/google'

const inter = Kumbh_Sans({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const BG = Bricolage_Grotesque({
  subsets: ['latin'],
  variable: '--font-bg',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${BG.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
          {/* <Banner /> */}
        </div>
      </body>
    </html>
  )
}
